# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  #secret_key_base: very_long_random_string # works but below is safer
  # secret_key_base below was created automatically with "$rails new ..."
  secret_key_base: ca7bb2b04d7718149e3e769fa5d26a37c17a106310edf778456fd5bd0f0c6d289437df7ce8e87b8a0c9530f89f648959d4be1c5791e6c12dcf0e6bf433917b08

test:
  #secret_key_base: very_long_random_string # works but below is safer
  # secret_key_base below was created automatically with "$rails new ..."
  secret_key_base: b21802d49e21f305b6162d6224a9c364828d4878d08af711eba35527e595b5be2a6789755d9500b54976b8d68f0dd052de67f91c7871b6fca55d969295de7a72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
